In [3]:
import pandas as pd

In [9]:
df = pd.read_csv("fifa_world_cup_2026_player_performance-selected-columns.csv")
df

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left
...,...,...,...,...,...,...,...,...,...,...
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right

In [10]:
df.head()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left

In [11]:
df.tail()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right

In [12]:
df.shape

(54600, 10)

In [13]:
df.columns

Index(['player_id', 'player_name', 'age', 'nationality', 'team',
       'jersey_number', 'position', 'height_cm', 'weight_kg',
       'preferred_foot'],
      dtype='str')

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   player_id       54600 non-null  str
 1   player_name     54600 non-null  str
 2   age             54600 non-null  int64
 3   nationality     54600 non-null  str
 4   team            54600 non-null  str
 5   jersey_number   54600 non-null  int64
 6   position        54600 non-null  str
 7   height_cm       54600 non-null  int64
 8   weight_kg       54600 non-null  int64
 9   preferred_foot  54600 non-null  str
dtypes: int64(4), str(6)
memory usage: 4.2 MB

In [15]:
df.dtypes

player_id           str
player_name         str
age               int64
nationality         str
team                str
jersey_number     int64
position            str
height_cm         int64
weight_kg         int64
preferred_foot      str
dtype: object

In [16]:
df.isnull().sum()

player_id         0
player_name       0
age               0
nationality       0
team              0
jersey_number     0
position          0
height_cm         0
weight_kg         0
preferred_foot    0
dtype: int64

In [17]:
df = df.drop_duplicates()
df

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left
...,...,...,...,...,...,...,...,...,...,...
5143,P00324,Philipp Friedl,24,Austrian,Austria,12,Defender,188,81,Right
5144,P00320,Stefan Hinteregger,24,Austrian,Austria,8,Defender,190,73,Right
5145,P00326,Marcel Dembir,22,Austrian,Austria,14,Midfielder,183,78,Right
5146,P00313,David Sabitzer,31,Austrian,Austria,1,Goalkeeper,192,75,Right
5147,P00314,Marcel Lainer,21,Austrian,Austria,2,Goalkeeper,192,77,Right

In [18]:
cleaned_df = pd.read_csv("cleaned_fifa_dataset.csv")
cleaned_df.head()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left

In [24]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

Missing Values:
player_id         0
player_name       0
age               0
nationality       0
team              0
jersey_number     0
position          0
height_cm         0
weight_kg         0
preferred_foot    0
dtype: int64

Duplicate Rows: 0

In [19]:
df.describe()

               age  jersey_number    height_cm    weight_kg
count  1248.000000    1248.000000  1248.000000  1248.000000
mean     26.303686      13.500000   181.633013    75.745192
std       4.071130       7.503007     6.266593     3.951081
min      17.000000       1.000000   163.000000    65.000000
25%      23.750000       7.000000   177.000000    73.000000
50%      26.000000      13.500000   182.000000    76.000000
75%      29.000000      20.000000   186.000000    78.000000
max      39.000000      26.000000   200.000000    87.000000

In [20]:
df.nunique()

player_id         1248
player_name       1245
age                 23
nationality         48
team                48
jersey_number       26
position             4
height_cm           37
weight_kg           22
preferred_foot       2
dtype: int64

In [21]:
df.to_csv("cleaned_fifa_dataset.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [22]:
cleaned_df = pd.read_csv("cleaned_fifa_dataset.csv")
cleaned_df.head()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left

In [23]:
cleaned_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1248 entries, 0 to 1247
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   player_id       1248 non-null   str
 1   player_name     1248 non-null   str
 2   age             1248 non-null   int64
 3   nationality     1248 non-null   str
 4   team            1248 non-null   str
 5   jersey_number   1248 non-null   int64
 6   position        1248 non-null   str
 7   height_cm       1248 non-null   int64
 8   weight_kg       1248 non-null   int64
 9   preferred_foot  1248 non-null   str
dtypes: int64(4), str(6)
memory usage: 97.6 KB